apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp3-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp3
  template: 
    metadata: # Dictionary
      name: myapp3-pod
      labels: # Dictionary 
        app: myapp3         
    spec:
      containers: # List
        - name: myapp3-container
          image: abhijeetatdhawale/mynginx_image2:v2
          ports:
            - containerPort: 80


    