apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp2-rs  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp2
  template: 
    metadata: # Dictionary
      name: myapp2-pod
      labels: # Dictionary 
        app: myapp2         
    spec:
      containers: # List
        - name: myapp2-container
          image: abhijeetatdhawale/mynginx_image2:v2
          ports:
            - containerPort: 80


    